matrix:
  include:
    - name: linux-py36
      language: python
      python: 3.6
      sudo: required
      services:
        - docker
      env:
        - TOXENV=py36
        - PIP=pip3
        - CIBW_BUILD=cp36-*
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      name: linux-py36
      language: python
      python: 3.6
      sudo: required
      services:
        - docker
      env:
        - TOXENV=py36
        - PIP=pip3
        - CIBW_BUILD=cp36-*

    - name: linux-py37
      language: python
      python: 3.7
      sudo: required
      services:
        - docker
      env:
        - TOXENV=py37
        - PIP=pip3
        - CIBW_BUILD=cp37-*
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      name: linux-py37
      language: python
      python: 3.7
      sudo: required
      services:
        - docker
      env:
        - TOXENV=py37
        - PIP=pip3
        - CIBW_BUILD=cp37-*

    - name: linux-py38
      language: python
      python: 3.8
      sudo: required
      services:
        - docker
      env:
        - TOXENV=py38
        - PIP=pip3
        - CIBW_BUILD=cp3!-*
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      name: linux-py38
      language: python
      python: 3.8
      sudo: required
      services:
        - docker
      env:
        - TOXENV=py38
        - PIP=pip3
        - CIBW_BUILD=cp38-*
    - name: pypy3.6
      language: python
      python: pypy3
      env:
        - TOXENV=pypy3
        - PIP=pip
      install:
        - ${PIP} install -U pip
        - ${PIP} install -r requirements.txt
      script:
        - tox
    - name: pypy3.6
      arch: arm64-graviton2
      virt: lxd
      group: edge
      language: python
      python: pypy3
      env:
        - TOXENV=pypy3
        - PIP=pip
      install:
        - ${PIP} install -U pip
        - ${PIP} install -r requirements.txt
      script:
        - tox

    - name: doctest38
      language: python
      python: 3.8
      env:
        - TOXENV=doctest38
        - PIP=pip
      install:
        - ${PIP} install -U pip
        - ${PIP} install -r requirements.txt
      script:
        - tox
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      name: doctest38
      language: python
      python: 3.8
      env:
        - TOXENV=doctest38
        - PIP=pip
      install:
        - ${PIP} install -U pip
        - ${PIP} install -r requirements.txt
      script:
        - tox

    - name: memorytest38
      language: python
      python: 3.8
      env:
        - TOXENV=memorytest38
        - PIP=pip
      install:
        - ${PIP} install -U pip
        - ${PIP} install -r requirements.txt
      script:
        - tox
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      name: memorytest38
      language: python
      python: 3.8
      env:
        - TOXENV=memorytest38
        - PIP=pip
      install:
        - ${PIP} install -U pip
        - ${PIP} install -r requirements.txt
      script:
        - tox

install:
  - ${PIP} install -U pip
  - ${PIP} install cibuildwheel==0.10.2
  - ${PIP} install -r requirements.txt
script:
  - tox
  #- git stash --all # Restore fresh checkout
  #- cibuildwheel --output-dir dist
# deployment can be added like:
#
# deploy:
#   - provider: pypi
#     # server: https://test.pypi.org/legacy/
#     user: user
#     password:
#       secure: "youwish"
#     distributions: "sdist"
#     skip_existing: true
#     skip_cleanup: true
#     on:
#       branch: master
#       tags: true
#
# or like https://github.com/joerick/cibuildwheel-autopypi-example/blob/master/.travis.yml#L21-L25
